# Provide path to that file as -Dlog4j.configuration=file:/path/to/log4j.properties
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %p %c: %m%n

log4j.rootLogger=INFO,console
log4j.threshhold=ALL

# Hadoop
log4j.logger.org.apache.hadoop=WARN
log4j.logger.org.apache.hadoop.mapreduce.Job=INFO
log4j.logger.org.apache.hadoop.util.NativeCodeLoader=ERROR

# Spark
log4j.logger.org.apache.spark.deploy=WARN
log4j.logger.org.apache.spark.network=WARN
log4j.logger.org.apache.spark.resource=WARN
log4j.logger.org.apache.spark.scheduler=WARN
log4j.logger.org.apache.spark.storage=WARN
log4j.logger.org.apache.spark.ui=WARN
log4j.logger.org.apache.spark.util=WARN
log4j.logger.org.apache.spark.MapOutputTrackerMasterEndpoint=WARN
log4j.logger.org.apache.spark.SparkContext=WARN
log4j.logger.org.apache.spark.SparkEnv=WARN
log4j.logger.org.apache.spark.SecurityManager=WARN
log4j.logger.org.sparkproject.jetty=WARN

# HBase
log4j.logger.org.apache.hbase=WARN
log4j.logger.org.apache.zookeeper=WARN
log4j.logger.org.apache.hadoop.hbase.zookeeper=WARN
log4j.logger.org.apache.hadoop.hbase.client=ERROR
